{% set version = "1.8.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-skpr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/skpr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/skpr/skpr_{{ version }}.tar.gz
  sha256: 20f8b362bd6717c99b72bfd101cfc2716349524c1af7974dc5971e644882907d

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=0.11.0
    - r-rcppeigen
    - r-car
    - r-dofuture
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-future
    - r-iterators
    - r-lazyeval
    - r-lme4
    - r-lmertest
    - r-magrittr
    - r-progress
    - r-progressr
    - r-scales
    - r-survival
    - r-viridis
  run:
    - r-base
    - r-rcpp >=0.11.0
    - r-rcppeigen
    - r-car
    - r-dofuture
    - r-doparallel
    - r-dorng
    - r-foreach
    - r-future
    - r-iterators
    - r-lazyeval
    - r-lme4
    - r-lmertest
    - r-magrittr
    - r-progress
    - r-progressr
    - r-scales
    - r-survival
    - r-viridis

test:
  commands:
    - $R -e "library('skpr')"           # [not win]
    - "\"%R%\" -e \"library('skpr')\""  # [win]

about:
  home: https://github.com/tylermorganwall/skpr
  license: GPL-3.0-only
  summary: Generates and evaluates D, I, A, Alias, E, T, and G optimal designs. Supports generation and evaluation of blocked and split/split-split/.../N-split plot designs. Includes parametric and Monte Carlo power evaluation functions, and supports calculating power for censored responses. Provides a framework to evaluate
    power using functions provided in other packages or written by the user. Includes a Shiny graphical user interface that displays the underlying code used to create and evaluate the design to improve ease-of-use and make analyses more reproducible.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - comatrion/r-skpr

# Package: skpr
# Title: Design of Experiments Suite: Generate and Evaluate Optimal Designs
# Version: 0.64.2
# Authors@R: c(person("Tyler", "Morgan-Wall", email = "tylermw@gmail.com", role = c("aut", "cre")), person("George", "Khoury", email = "george.m.khoury@gmail.com", role = c("aut")))
# Description: Generates and evaluates D, I, A, Alias, E, T, and G optimal designs. Supports generation and evaluation of blocked and split/split-split/.../N-split plot designs. Includes parametric and Monte Carlo power evaluation functions, and supports calculating power for censored responses. Provides a framework to evaluate power using functions provided in other packages or written by the user. Includes a Shiny graphical user interface that displays the underlying code used to create and evaluate the design to improve ease-of-use and make analyses more reproducible.
# Copyright: Institute for Defense Analyses
# Depends: R (>= 3.0.2), shiny
# License: GPL-3
# LazyData: true
# RoxygenNote: 7.0.2
# Imports: utils, iterators, stats, nlme, lme4, Rcpp (>= 0.11.0), rintrojs, shinythemes, foreach, doParallel, survival, knitr, kableExtra, doRNG, future, promises, shinyjs, car, viridis, magrittr, lmerTest, methods, lazyeval, base64enc, crayon
# LinkingTo: Rcpp, RcppEigen
# Suggests: testthat
# Encoding: UTF-8
# URL: https://github.com/tylermorganwall/skpr
# BugReports: https://github.com/tylermorganwall/skpr/issues
# NeedsCompilation: yes
# Packaged: 2020-03-04 18:27:08 UTC; tmorganw
# Author: Tyler Morgan-Wall [aut, cre], George Khoury [aut]
# Maintainer: Tyler Morgan-Wall <tylermw@gmail.com>
# Repository: CRAN
# Date/Publication: 2020-03-04 20:20:02 UTC
